credentials:
  usernames:
    CharlieG:
      email: charlie@dataunioncafe.com
      name: Charlie Gale
      password: $2b$12$6VSp4ekHF2Qhh6WOanqOmuggDetbgmUrsrwUC1asNsotwsdSIjsM. # To be replaced with hashed password
    # rbriggs:
    #   email: rbriggs@gmail.com
    #   name: Rebecca Briggs
    #   password: def # To be replaced with hashed password
cookie:
  expiry_days: 0
  key: random_signature_key # Must be string
  name: random_cookie_name
preauthorized:
  emails:
    - melsby@gmail.com
